Update autopep8_check.yml

diff --git a/.github/workflows/autopep8_check.yml b/.github/workflows/autopep8_check.yml
--- a/.github/workflows/autopep8_check.yml
+++ b/.github/workflows/autopep8_check.yml
@@ -34,7 +34,26 @@ jobs:
         else
           echo "status=pass" >> $GITHUB_ENV
         fi
-        
+
+    # enter the critical section    
+    - name: Retry Lock File Creation
+      run: |
+        MAX_RETRIES = 10
+        RETRY_INTERVAL = 3
+        LOCK_FILE=".github/lockfile"
+        for i in $(seq 1 $MAX_RETRIES); do
+          if [ -f "$LOCK_FILE" ]; then
+            echo "Another workflow is running. Retry $i/$MAX_RETRIES."
+            sleep $RETRY_INTERVAL
+          else
+            echo "Creating lock file."
+            touch "$LOCK_FILE"
+            exit 0
+          fi
+        done
+        echo "Failed to create lock file after $MAX_RETRIES retries."
+        exit 1
+
     - name: Commit files # commit the output folder
       run: |
         git config --local user.email "test@github.com"
@@ -43,7 +62,17 @@ jobs:
         git add ./post_traces/autopep8_trace.txt
         git commit --allow-empty -m "Update autopep8 report"
         git push
-           
+      continue-on-error: true
+
+    # leave the critical section    
+    - name: Remove Lock File
+      run: |
+        LOCK_FILE=".github/lockfile"
+        if [ -f "$LOCK_FILE" ]; then
+          echo "Removing lock file."
+          rm "$LOCK_FILE"
+        fi
+    
     - name: Create Awesome Badge
       uses: schneegans/dynamic-badges-action@v1.7.0
       with:
